### ISSUE TITLE
Unable to install on Laravel 5.1.43

### ISSUE THREAD

**Issue by Focus3D** [php-soft/laravel-users#100]
Hi,
Fresh Laravel 5.1.43 install
run composer require php-soft/laravel-users:dev-master and getting this error:
Your requirements could not be resolved to an installable set of packages.
 Problem 1
    - Installation request for php-soft/laravel-users dev-master -> satisfiable by php-soft/laravel-users[dev-master].
    - php-soft/laravel-users dev-master requires zizaco/entrust dev-laravel-5 -> satisfiable by zizaco/entrust[dev-laravel-5] but these conflict with your requirements or minimum-stability.

**Comment by huytbt** [comment]
Hi @Focus3D. Can you please try with php-soft/laravel-users:1.0.0. It's support laravel 5.1.*
