### ISSUE TITLE
how to auth by postman

### ISSUE THREAD

**Issue by essivision** [php-soft/laravel-users#98]
Hi
How to config POSTMAN for access REST API without add token as manually?

Thanks

**Comment by huytbt** [comment]
@essivision: You can use header: Authorization = "Bearer " + access_token

**Comment by essivision** [comment]
I want to add email and password to POSTMAN and itself get token and set in header. Is it possible?

**Comment by toancong** [comment]
@essivision : You can login with email password then set the token in APIs. I don't know if postman cant hold process you want, but it has Manage Preset feature which help you quickly use/change predefined values
